In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('datasets/swmh/train.csv')

In [5]:
data.head()

                                                text              label
0  wanting to skip or postpone my exam my exam is...       self.Anxiety
1  Do other bipolar folks have problems with subs...       self.bipolar
2  Wanted to share some revelations I just had to...    self.depression
3  I feel deader than dead. I find that I don't h...  self.SuicideWatch
4  I'm pretty sure my friends suicidal what do I ...  self.SuicideWatch

In [8]:
data1 = pd.read_csv('datasets/swmh/test.csv')

In [13]:
data1.head()

                                                text              label
0  Suicidal, but won't do it. Just need someone t...  self.SuicideWatch
1  A lie. A lie ruined my life A lie.\n\n\nA lie ...    self.offmychest
2  Suicidal Thoughts and Venting I would first li...  self.SuicideWatch
3  Guided Meditation Disclaimer:  I am in no way ...       self.bipolar
4  Effexor day 1 is going badly Good news! So the...       self.Anxiety

In [10]:
data2 = pd.read_csv('datasets/swmh/val.')

In [11]:
data2.head()

                                                text              label
0  I can't make money I can't live in a world whe...       self.bipolar
1  "How are you?" "I'm fine," "How are you?" "I'm...    self.offmychest
2  I'm fed up I'm fed up with all this world, it'...  self.SuicideWatch
3  Can depression "evolve" to bipolar over time w...       self.bipolar
4  Any words of encouragement Hello I posted year...    self.depression

In [15]:
#concat
concat = pd.concat([data,data1,data2])

In [16]:
concat

                                                   text              label
0     wanting to skip or postpone my exam my exam is...       self.Anxiety
1     Do other bipolar folks have problems with subs...       self.bipolar
2     Wanted to share some revelations I just had to...    self.depression
3     I feel deader than dead. I find that I don't h...  self.SuicideWatch
4     I'm pretty sure my friends suicidal what do I ...  self.SuicideWatch
...                                                 ...                ...
8701  I stopped Lamictal after it screwed up my visi...       self.bipolar
8702  I'm afraid my ex committed suicide what do I d...  self.SuicideWatch
8703  Failed college 2 times it was +10 years ago. I...    self.depression
8704  Put on some music that you find beautiful and ...       self.Anxiety
8705  Discovered that my friend made a blog and toda...    self.depression

[54412 rows x 2 columns]

In [25]:
concat1 = pd.concat([data,data1,data2], axis=0, ignore_index=True)

In [26]:
concat1.head(50)

                                                 text              label
0   wanting to skip or postpone my exam my exam is...       self.Anxiety
1   Do other bipolar folks have problems with subs...       self.bipolar
2   Wanted to share some revelations I just had to...    self.depression
3   I feel deader than dead. I find that I don't h...  self.SuicideWatch
4   I'm pretty sure my friends suicidal what do I ...  self.SuicideWatch
5   Self-harm urges are getting stronger Hey every...    self.depression
6   Anonymous Entry: plz be nice My brain boils no...    self.depression
7   I'm drowning. I don't remember ever really bei...    self.depression
8   ANYONE here ever tried r-TMS (repeated Transcr...       self.bipolar
9   Anyone else just afraid of life? First off, if...    self.depression
10  Serious Question about suicide Why do we have ...    self.depression
11  i dont know why it bothers me when my friend t...    self.depression
12  I just took about 30 anxiety pills. I doubt it...    self.depression
13  I want to have a baby so someone will love me ...    self.offmychest
14  Therapy For The Caregiver/Non Anxious Partner?...       self.Anxiety
15  Extreme Anxiety before exams Hi, all. I've nev...       self.Anxiety
16  shouldn't have been born long story short, I h...    self.depression
17  I have a presentation in 7 hours, and I'm alre...       self.Anxiety
18  I wish friendships never ended... I am current...    self.offmychest
19  i'm going to be hopefully dead before the end ...  self.SuicideWatch
20  Is it just me or ... Does it feel like people ...  self.SuicideWatch
21  Anybody else suddenly recall a childhood memor...       self.Anxiety
22  When clinically depressed person says they don...    self.depression
23  Sorry so needy, up since 2am This sleep thing ...       self.bipolar
24  A terrible friend I have a crazy story to tell...    self.offmychest
25    I think this is the place to say this [deleted]  self.SuicideWatch
26  Last night I (21/F) had an intense anxiety att...       self.Anxiety
27  I’m gonna do it tonight I’ve attempted 4 times...  self.SuicideWatch
28  I feel like it's creeping up on me After a hug...    self.depression
29  My friend is saying suicidal things and i'm wo...  self.SuicideWatch
30  I'm alone so so so alone I suck at making frie...    self.depression
31  I hate diverticulitis I have diverticulosis. A...    self.offmychest
32  If your partner told you they felt suicidal wh...    self.depression
33  I hate staying alive for others I really reall...    self.depression
34  I have evolved from a cactus... ...into a moth...    self.depression
35  I can't sleep, I can't stop thinking about you...    self.offmychest
36  I fell in love while travelling, and ruined it...    self.offmychest
37  Just soo tired My god I'm so tired...tired of ...    self.offmychest
38  Can someone help? For background, I'm in high ...  self.SuicideWatch
39  I love two people I am a married man. The woma...    self.offmychest
40  I could really use some good vibes right now. ...  self.SuicideWatch
41  My family are causing me depression and anxiet...    self.depression
42  Posting this in someone else's stead G'day, ev...  self.SuicideWatch
43  always back to being suicidal have no dreams o...  self.SuicideWatch
44  Does anyone else feel like they are subconscio...    self.depression
45  Please be 100% honest... How stupid is it to k...  self.SuicideWatch
46  22/F feeling overwhelmed Hi y’all, as the titl...       self.bipolar
47  Medication Anyone on here take lexapro and if ...       self.Anxiety
48  I hate this I'm never going to get any better....    self.depression
49  today I asked 6 different people if they wante...    self.depression

In [27]:
concat1.to_csv("swmh.csv")

In [28]:
concat1.to_csv("datasets/swmh/swmh.csv", index=False)

## NOW WE CAN USE THE swmh DATASET